providers = ["node"]

[phases.setup]
nixPkgs = ['...']
aptPkgs = [
    "libfontconfig1",
    "libfontconfig1-dev",
    "libxrender-dev",
    "fontconfig",
    "build-essential",
    "gcc"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview"